<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataIDProviders = array (
  'https://whoami.cesnet.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://whoami.cesnet.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'CESNET',
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://idp.hostel.eduid.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.hostel.eduid.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Hostel',
    'en' => 
    array (
      'Name' => 'Hostel',
    ),
    'cs' => 
    array (
      'Name' => 'Hostel',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://eduid.fno.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://eduid.fno.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Fakultní nemocnice Ostrava',
    'cs' => 
    array (
      'Name' => 'Fakultní nemocnice Ostrava',
    ),
    'en' => 
    array (
      'Name' => 'University Hospital Ostrava',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://idp.asu.cas.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.asu.cas.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Astronomický ústav Akademie věd České Republiky',
    'en' => 
    array (
      'Name' => 'Astronomical Institute of the Czech Academy of Sciences',
    ),
    'cs' => 
    array (
      'Name' => 'Astronomický ústav Akademie věd České Republiky',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://idp.ugn.cas.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.ugn.cas.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Ústav geoniky AV ČR',
    'en' => 
    array (
      'Name' => 'Institute of Geonics of the CAS',
    ),
    'cs' => 
    array (
      'Name' => 'Ústav geoniky AV ČR',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://whoami-dev.cesnet.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://whoami-dev.cesnet.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'CESNET (whoami-dev)',
    'en' => 
    array (
      'Name' => 'CESNET (whoami-dev)',
    ),
    'cs' => 
    array (
      'Name' => 'CESNET (whoami-dev)',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://idp2.ics.muni.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp2.ics.muni.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Masarykova univerzita',
    'en' => 
    array (
      'Name' => 'Masaryk University',
    ),
    'cs' => 
    array (
      'Name' => 'Masarykova univerzita',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://wsso.vscht.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://wsso.vscht.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Vysoká škola chemicko-technologická Praze',
    'en' => 
    array (
      'Name' => 'University of Chemistry and Technology, Prague',
    ),
    'cs' => 
    array (
      'Name' => 'Vysoká škola chemicko-technologická Praze',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://shibboleth3.nkp.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibboleth3.nkp.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Narodni knihovna Ceske republiky',
    'en' => 
    array (
      'Name' => 'The National Library of the Czech Republic',
    ),
    'cs' => 
    array (
      'Name' => 'Narodni knihovna Ceske republiky',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://shib2.zcu.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://shib2.zcu.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Západočeská univerzita v Plzni',
    'en' => 
    array (
      'Name' => 'University of West Bohemia',
    ),
    'cs' => 
    array (
      'Name' => 'Západočeská univerzita v Plzni',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://whoami.vsb.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://whoami.vsb.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'Vysoká škola báňská - Technická univerzita Ostrava',
    'en' => 
    array (
      'Name' => 'VŠB-Technical University of Ostrava',
    ),
    'cs' => 
    array (
      'Name' => 'Vysoká škola báňská - Technická univerzita Ostrava',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
  'https://idp.vsb.cz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.vsb.cz/idp/profile/Shibboleth/SSO',
    'Name' => 'VSB-TUO',
    'en' => 
    array (
      'Name' => 'VSB-TUO',
    ),
    'cs' => 
    array (
      'Name' => 'VSB-TUO',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
)
?>