<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array (
  'https://devnull.cesnet.cz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://devnull.cesnet.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'CESNET',
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://devnull.cesnet.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://edev.cesnet.cz/sp/shibboleth/cztestfed2' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/Login',
      1 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/DS',
      2 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/DS_VO',
    ),
    'Name' => 'CESNET, z. s. p. o.',
    'cs' => 
    array (
      'Name' => 'CESNET, z. s. p. o.',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML2/POST',
      1 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML2/ECP',
      4 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML/POST',
      5 => 'https://edev.cesnet.cz/cztestfed2/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://publikace-test.cesnet.cz/sp/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'CESNET',
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://publikace-test.cesnet.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://oc-test.du.cesnet.cz/shibboleth/sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'CESNET',
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://ufal-point-dev.ms.mff.cuni.cz/shibboleth/eduid/sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'Ústav formální a aplikované lingvistiky',
    'cs' => 
    array (
      'Name' => 'Ústav formální a aplikované lingvistiky',
    ),
    'en' => 
    array (
      'Name' => 'Institute of Formal and Applied Linguistics',
    ),
    'ACURL' => 
    array (
      0 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://ufal-point-dev.ms.mff.cuni.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://attributes.eduid.cz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attributes.eduid.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'CESNET',
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://atributy.eduid.cz/Shibboleth.sso/SAML/Artifact',
      6 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML2/POST',
      7 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      8 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML2/Artifact',
      9 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML2/ECP',
      10 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML/POST',
      11 => 'https://attributes.eduid.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://uzivatel.sso.vsb.cz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'VŠB - Technická univerzita Ostrava',
    'cs' => 
    array (
      'Name' => 'VŠB - Technická univerzita Ostrava',
    ),
    'en' => 
    array (
      'Name' => 'VSB - Technical University of Ostrava',
    ),
    'ACURL' => 
    array (
      0 => 'https://as1-test.wps.vsb.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML2/POST',
      2 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      3 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML2/Artifact',
      4 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML2/ECP',
      5 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML/POST',
      6 => 'https://uzivatel.sso.vsb.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://new.foodle.cz/simplesamlphp' => 
  array (
    'Name' => 'Foodle.CZ',
    'cs' => 
    array (
      'Name' => 'Foodle.CZ',
    ),
    'en' => 
    array (
      'Name' => 'Foodle.CZ',
    ),
    'ACURL' => 
    array (
      0 => 'https://new.foodle.cz/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
      1 => 'https://new.foodle.cz/simplesaml/module.php/saml/sp/saml1-acs.php/default-sp',
      2 => 'https://new.foodle.cz/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
      3 => 'https://new.foodle.cz/simplesaml/module.php/saml/sp/saml1-acs.php/default-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://physiome.lf1.cuni.cz' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'Ustav patologicke fyziologie',
    'cs' => 
    array (
      'Name' => 'Ustav patologicke fyziologie',
    ),
    'en' => 
    array (
      'Name' => 'Institute of Pathological Physiology',
    ),
    'ACURL' => 
    array (
      0 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://app.physiovalues.org/Shibboleth.sso/SAML2/POST',
      2 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML2/POST',
      3 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      4 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML2/Artifact',
      5 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML2/ECP',
      6 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML/POST',
      7 => 'https://physiome.lf1.cuni.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://oc-test.du.cesnet.cz/shibboleth/sp2' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/Login',
    ),
    'Name' => 'CESNET',
    'cs' => 
    array (
      'Name' => 'CESNET',
    ),
    'en' => 
    array (
      'Name' => 'CESNET',
    ),
    'ACURL' => 
    array (
      0 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://karotka.du.cesnet.cz/Shibboleth.sso/SAML/Artifact',
      6 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/POST',
      7 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      8 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/Artifact',
      9 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML2/ECP',
      10 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML/POST',
      11 => 'https://oc-test.du.cesnet.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
)
?>